### ISSUE TITLE
About the Source Code of Term 1 Simulator

### ISSUE THREAD

**Issue by AlexanderInUM** [asujaykk/Self-Driving-car#1]
Hi! Fine to see your project.
Do you know where I can find **the source code for the Udacity's Term 1 simulator**?
I've checked the [Udavity's repository](https://github.com/udacity/self-driving-car-sim/releases) **but** its releases are now only contains Term 2 and 3.

**Comment by asujaykk** [comment]
Hi Alexander,
First of all I'm a bit confused about your query,
what do you really need?  is it the precompiled " term1 simulator " or the source code used to create "term1 simulator"? 
If you want the precompiled  " term1 simulator "  then please find it in this repo (https://github.com/udacity/self-driving-car-sim.git)

![Untitled](https://user-images.githubusercontent.com/78997596/226699189-6bb15e1d-2362-4117-8396-c0a863824424.jpeg)

But if you want the source code to build "term1 simulator", then  please get in touch with  udacity developer team/ repo owners. 
In this project we are not building the simulator from source, instead we are using precompiled simulator.

**Comment by asujaykk** [comment]
hello [AlexanderInUM](https://github.com/AlexanderInUM), did I answered your query?

**Comment by AlexanderInUM** [comment]
Yes~ Thanks a lot!
