### ISSUE TITLE
conda environment issue

### ISSUE THREAD

**Issue by Tluc22** [asujaykk/Self-Driving-car#3]
I am not able to create a conda environment for some reason even though i copy pasted the code "conda env create -f  autopilot_project/Self-Driving-car/anaconda_env/tens_gpu_self_driving_car.yaml",is it because Im using windows and there is a different command for it?
![image_2023-04-21_100912430](https://user-images.githubusercontent.com/130377578/233542174-11083517-ff8b-4610-92b6-19f2f1e9a156.png)

**Comment by asujaykk** [comment]
The conda environment  yaml file  [tens_gpu_self_driving_car.yaml](https://github.com/asujaykk/Self-Driving-car/blob/main/anaconda_env/tens_gpu_self_driving_car.yaml) was created from a working inux conda environment, which include system dependencies as well. So it may fail  if you are try to re-create the conda environment in windows os,

let me try to prepare the env.yaml without system dependencies and if it works in windows, then i will update it here.

**Comment by Tluc22** [comment]
thank you, really appreciate your help but can you tell me when will you be updating it here

**Comment by asujaykk** [comment]
Please find the conda env yaml file created from win10 here https://github.com/asujaykk/Self-Driving-car/blob/main/anaconda_env/for_windows/self_driving_car_mod_dep_no_builds.yamlaml

**Comment by Tluc22** [comment]
![image](https://user-images.githubusercontent.com/130377578/233823285-ce17a701-852a-4b1a-be83-a9594e509235.png)

It is showing me this in train log after typing the model_train.py, also i changed python3 to python since it wasnt addressing python3 as a command 

![image](https://user-images.githubusercontent.com/130377578/233823260-b558bc9a-2354-40f5-a506-05d73a3d9800.png)

**Comment by asujaykk** [comment]
please check the executed command once again. I can see character "c" at the end of the executed command which is not expected.
 the end of the commad should be  "1>train.log 2>&1".
 
One more point, I modified "model_train.py" in this repo, so that it will generate output files properly in windows environment as well.
